collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9612517233472317
  brandStrength: 0.8780881
  lightness: 0.1725401233416051
  brandColors:
    - '#FFFFFF'
    - '#0E1215'
    - '#AFAA94'
    - '#B94224'
    - '#96E6FC'
  rhythmicContrast: 0.2529110547620803
typography_spectrum: 0.1949517
navigation:
  - id: 'http://ettoreink.com/'
    url: 'http://ettoreink.com/'
    name: Website
    type: external
layout_spectrum: 0
name: Ettore Ink
